Bug-01
Exception in thread "main"
org.springframework.dao.InvalidDataAccessApiUsageException: detached entity passed to persist: br.ufjf.dcc193.trabalhoum.model.Sede; nested exception is org.hibernate.PersistentObjectException: detached entity passed to persist: br.ufjf.dcc193.trabalhoum.model.Sede

Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: br.ufjf.dcc193.trabalhoum.model.Sede
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:127)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:823)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:790)